@include('Web.@components.top')
@if(\Request::is('admin'))
    @include('Web.pages.Dashboard')
@elseif(\Request::is('admin/pages/view/daftar_anggota'))
    @include('Web.pages.Daftar_Anggota')
@elseif(\Request::is('admin/pages/view/daftar_user'))
    @include('Web.pages.Daftar_User')
@endif
@include('Web.@components.bottom')